// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHTBhL0-YqP-xloik8EfCHLKUjrkE60rE',
    appId: '1:657237127243:web:7f6d37b23ebd98f400ddce',
    messagingSenderId: '657237127243',
    projectId: 'real-time-chat-app-98210',
    authDomain: 'real-time-chat-app-98210.firebaseapp.com',
    storageBucket: 'real-time-chat-app-98210.firebasestorage.app',
    measurementId: 'G-GR04FG5VBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfPFjBMeVPH-qAG05IRw-45iJlC7PkRmc',
    appId: '1:657237127243:android:0968471cbefb70a000ddce',
    messagingSenderId: '657237127243',
    projectId: 'real-time-chat-app-98210',
    storageBucket: 'real-time-chat-app-98210.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkhwJbJixrD4nQ1NG134KfXdLmV62iWuc',
    appId: '1:657237127243:ios:9066ed0d4c3cba6a00ddce',
    messagingSenderId: '657237127243',
    projectId: 'real-time-chat-app-98210',
    storageBucket: 'real-time-chat-app-98210.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkhwJbJixrD4nQ1NG134KfXdLmV62iWuc',
    appId: '1:657237127243:ios:9066ed0d4c3cba6a00ddce',
    messagingSenderId: '657237127243',
    projectId: 'real-time-chat-app-98210',
    storageBucket: 'real-time-chat-app-98210.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHTBhL0-YqP-xloik8EfCHLKUjrkE60rE',
    appId: '1:657237127243:web:82bdc8553db9731400ddce',
    messagingSenderId: '657237127243',
    projectId: 'real-time-chat-app-98210',
    authDomain: 'real-time-chat-app-98210.firebaseapp.com',
    storageBucket: 'real-time-chat-app-98210.firebasestorage.app',
    measurementId: 'G-TM80CRBYTV',
  );
}
